### ISSUE TITLE
Users can't register after first registration

### ISSUE THREAD

**Issue by nitinmukesh** [danielfsousa/express-rest-boilerplate#608]
Hello,

I am using postman
The first user registered successfully. After that I am getting this error what data I change

http://localhost:3000/v1/auth/register

```
{
    "code": 409,
    "message": "Validation Error",
    "errors": [
        {
            "field": "email",
            "location": "body",
            "messages": [
                "\"email\" already exists"
            ]
        }
    ],
    "stack": "MongoError: E11000 duplicate key error collection: test.users index: username_1 dup key: { username: null }\n    at Function.create (C:\\Users\\nitin\\Desktop\\express-rest-boilerplate-main\\node_modules\\mongodb\\lib\\core\\error.js:59:12)\n    at toError (C:\\Users\\nitin\\Desktop\\express-rest-boilerplate-main\\node_modules\\mongodb\\lib\\utils.js:130:22)\n    at C:\\Users\\nitin\\Desktop\\express-rest-boilerplate-main\\node_modules\\mongodb\\lib\\operations\\common_functions.js:258:39\n    at handler (C:\\Users\\nitin\\Desktop\\express-rest-boilerplate-main\\node_modules\\mongodb\\lib\\core\\sdam\\topology.js:961:24)\n    at C:\\Users\\nitin\\Desktop\\express-rest-boilerplate-main\\node_modules\\mongodb\\lib\\cmap\\connection_pool.js:352:13\n    at handleOperationResult (C:\\Users\\nitin\\Desktop\\express-rest-boilerplate-main\\node_modules\\mongodb\\lib\\core\\sdam\\server.js:567:5)\n    at MessageStream.messageHandler (C:\\Users\\nitin\\Desktop\\express-rest-boilerplate-main\\node_modules\\mongodb\\lib\\cmap\\connection.js:308:5)\n    at MessageStream.emit (events.js:315:20)\n    at processIncomingData (C:\\Users\\nitin\\Desktop\\express-rest-boilerplate-main\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:144:12)\n    at MessageStream._write (C:\\Users\\nitin\\Desktop\\express-rest-boilerplate-main\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:42:5)\n    at writeOrBuffer (internal/streams/writable.js:358:12)\n    at MessageStream.Writable.write (internal/streams/writable.js:303:10)\n    at TLSSocket.ondata (internal/streams/readable.js:719:22)\n    at TLSSocket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)"
}
```

This is the only data in database
```
{
  "_id": {
    "$oid": "62fde79ae3c8a51d6c92a68f"
  },
  "role": "admin",
  "password": "$2a$10$2PY14FUZOh0HL2",
  "email": "test@test.com",
  "createdAt": {
    "$date": {
      "$numberLong": "1660807066778"
    }
  },
  "updatedAt": {
    "$date": {
      "$numberLong": "1660807066778"
    }
  },
  "__v": 0
}
```

**Comment by nitinmukesh** [comment]
Fixed the issue

Either pass "name" during registration or

In user.model.js
```
  name: {
    type: String,
    maxlength: 128,
    index: true,
    trim: true,
  }
```
remove index: true
